# action.yml
name: 'Build'
description: 'Build'
inputs:
  platform:  # id of input
    description: 'Platform'
    required: true
    default: 'StandaloneWindows64'
  buildName:  # id of input
    description: 'Name of the build'
    required: true
    default: 'ExampleProjectName'
  license:
    description: 'Unity ulf-file'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'