name: CI

on:
  push:
    branches:    
      - feature/github-ci

jobs:
  build_WebGL:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/buildProject
      with:
        license: ${{ secrets.UNITY_LICENSE_CONTENT }}
        platform: WebGL
        buildName: ${{ secrets.PROJECT_NAME }}
    - run: cp -rf ./Builds/WebGL/${{ secrets.PROJECT_NAME }}/ ${{ secrets.PROJECT_NAME }}
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v2
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_PAT }}
        BRANCH: gh-pages
        FOLDER: ${{ secrets.PROJECT_NAME }}
        BASE_BRANCH: master