name: CI

on:
  push:
    branches:    
      - feature/github-ci

jobs:
  test-playmode:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/test
      with:
        cypher: ${{ secrets.LICENSE_SECRET }}
        mode: playmode
