name: CI

on:
  push:
    branches:    
      - feature/github-ci

jobs:
  build_WebGL:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build project
      id: buildStep
      uses: webbertakken/unity-builder@v0.1
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE_CONTENT }}
        UNITY_PROJECT_PATH: path/to/your/project
        BUILD_NAME: ${{ secrets.PROJECT_NAME }}
        BUILDS_PATH: build
        BUILD_TARGET: WebGL
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v2
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_PAT }}
        BRANCH: gh-pages
        FOLDER: ${{ steps.buildStep.outputs.allBuildsPath }}
        BASE_BRANCH: master