name: CI

on:
  push:
    branches:    
      - feature/github-ci

jobs:
  test-playmode:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: AlexanderDykov/unity-test-action@unity3d_2019.1.14f1
      with:
        license: ${{ secrets.UNITY_LICENSE_CONTENT }}
        mode: playmode